# 🛠 Feature Engineering – Complete Guide

Feature Engineering is the process of **transforming raw data into meaningful features** that help machine learning models make better predictions.  

It is one of the **most important steps** in the ML workflow because **good features often improve model performance more than complex algorithms**.

---

## **1️⃣ What is Feature Engineering?**
- Turning raw, messy data into **structured and useful input** for ML models.  
- Examples:  
  - From `Date of Birth` → extract `Age`  
  - From `Transaction Amount` → create `High Value Transaction` flag  
- Goal: Make patterns **easier for the model to learn**.

---

## **2️⃣ Prerequisites for Feature Engineering**
Before starting feature engineering, students should understand:  
1. **Types of data** – numeric, categorical, text, date/time.  
2. **Missing values** – know how to identify null/missing entries.  
3. **Outliers** – extreme values that may distort results.  
4. **Data distributions** – understand how values vary across features.  
5. **Correlation & relationships** – basic understanding of how features relate to target variable.  

✅ Optional but helpful: basic **Python pandas and numpy skills**, and **data visualization** (histograms, boxplots).

---

## **3️⃣ Steps to Perform Feature Engineering**

Here’s a step-by-step approach:

1. **Understand your dataset**  
   - Explore features, data types, missing values, outliers  
   - Visualize distributions  

2. **Handle missing values**  
   - Fill with mean/median/mode or drop rows/columns  

3. **Encode categorical variables**  
   - One-hot encoding, label encoding, or ordinal encoding  

4. **Scale / normalize features**  
   - Standardization (mean=0, std=1)  
   - Normalization (scale to 0–1)  

5. **Create new features**  
   - Combine existing features or extract new insights  
   - Examples: Age from DOB, total amount from item prices  

6. **Select important features**  
   - Remove irrelevant or noisy features  
   - Methods: correlation analysis, feature importance, variance threshold  

7. **Handle outliers**  
   - Detect extreme values and either remove, cap, or transform them  

8. **Document your transformations**  
   - Keep track of all changes to data for reproducibility  

---

Next, we will give **Python examples** for each of these steps, so students can **see feature engineering in action**.

In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('/content/house_prices.csv')
df

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116041,116041,3 BHK Ready to Occupy Flat for sale in Gayatri...,"This lovely 3 BHK Flat in Dwarka Sector 10, Ne...",1.88 Cr,11059.0,new-delhi,1300 sqft,Ready to Move,4 out of 8,Resale,...,North - East,"Garden/Park, Main Road",Gayatri Appartment,2,4,"1 Covered,",Freehold,NaN,NaN,NaN
116042,116042,3 BHK Ready to Occupy Flat for sale in DDA Fla...,3 BHK flat available for sale in New Delhi in ...,1.65 Cr,8919.0,new-delhi,1450 sqft,Ready to Move,1 out of 4,Resale,...,North - West,Main Road,DDA Flats Sarita Vihar,2,1,NaN,Freehold,NaN,NaN,NaN
116043,116043,3 BHK Ready to Occupy Flat for sale in Anekant...,Have a look at this immaculate 3 BHK flat for ...,90 Lac,6923.0,new-delhi,1200 sqft,Ready to Move,3 out of 4,Resale,...,East,"Garden/Park, Main Road",Anekant Apartment,3,2,NaN,Freehold,NaN,NaN,NaN
116044,116044,3 BHK Ready to Occupy Flat for sale Chittaranj...,"Chittaranjan Park, New Delhi has an attractive...",2 Cr,17778.0,new-delhi,1000 sqft,Ready to Move,1 out of 4,Resale,...,East,"Garden/Park, Main Road",NaN,3,3,NaN,Freehold,NaN,NaN,NaN
116045,116045,3 BHK Ready to Occupy Flat for sale in Fancy A...,3 BHK flat available for sale in New Delhi in ...,1.60 Cr,11429.0,new-delhi,1250 sqft,Ready to Move,1 out of 7,Resale,...,NaN,NaN,Fancy Apartments,2,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116046 entries, 0 to 116045
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              116046 non-null  int64
 1   Title              116046 non-null  object
 2   Description        113685 non-null  object
 3   Amount(in rupees)  116046 non-null  object
 4   Price (in rupees)  104807 non-null  float64
 5   location           116046 non-null  object
 6   Carpet Area        58861 non-null   object
 7   Status             115680 non-null  object
 8   Floor              110465 non-null  object
 9   Transaction        116004 non-null  object
 10  Furnishing         113901 non-null  object
 11  facing             69955 non-null   object
 12  overlooking        61232 non-null   object
 13  Society            43549 non-null   object
 14  Bathroom           115599 non-null  object
 15  Balcony            80977 non-null   object
 16  Car Parking        50111 non-null   object
 17  Ownership          70840 non-null   object
 18  Super Area         56442 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 18.6+ MB

In [ ]:
df['Amount(in rupees)'].unique()

array(['42 Lac ', '98 Lac ', '1.40 Cr ', ..., '1.5 Lac ', '24.4 Lac ',
       '9.90 Cr '], shape=(1561,), dtype=object)

In [ ]:
df[['Current_Floor', 'Total_Floors']] = df['Floor'].str.split(' out of ', expand=True)
df

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Current_Floor,Total_Floors
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN,10,11
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN,3,22
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN,10,29
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,3
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,20,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.0,zirakpur,NaN,Ready to Move,2 out of 4,New Property,...,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft,NaN,NaN,2,4
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.0,zirakpur,NaN,Ready to Move,4 out of 6,Resale,...,Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft,NaN,NaN,4,6
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,1 out of 3,Resale,...,Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN,NaN,NaN,1,3
187529,187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.0,zirakpur,NaN,Ready to Move,2 out of 2,Resale,...,Friends Enclave,2,NaN,NaN,NaN,709 sqft,NaN,NaN,2,2
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,5 out of 13,Resale,...,Affinity Greens,4,4,1 Covered,Freehold,1915 sqft,NaN,NaN,5,13

In [ ]:
df.drop(columns=['Floor','Index','Title','Description'], axis=1, inplace=True)
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Current_Floor,Total_Floors
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN,10,11
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN,3,22
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN,10,29
3,25 Lac,NaN,thane,530 sqft,Ready to Move,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,3
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,20,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,New Property,Semi-Furnished,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft,NaN,NaN,2,4
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,Resale,Unfurnished,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft,NaN,NaN,4,6
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,Resale,Furnished,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN,NaN,NaN,1,3
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,Resale,Semi-Furnished,NaN,Main Road,Friends Enclave,2,NaN,NaN,NaN,709 sqft,NaN,NaN,2,2
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft,NaN,NaN,5,13

In [ ]:
print(df)

       Amount(in rupees)  Price (in rupees)  location Carpet Area  \
0                42 Lac              6000.0     thane    500 sqft
1                98 Lac             13799.0     thane    473 sqft
2               1.40 Cr             17500.0     thane    779 sqft
3                25 Lac                 NaN     thane    530 sqft
4               1.60 Cr             18824.0     thane    635 sqft
...                  ...                ...       ...         ...
187526           63 Lac              3225.0  zirakpur         NaN
187527           55 Lac              3274.0  zirakpur         NaN
187528           76 Lac              4343.0  zirakpur   1250 sqft
187529           30 Lac              4231.0  zirakpur         NaN
187530          1.18 Cr              6162.0  zirakpur         NaN

               Status   Transaction      Furnishing        facing  \
0       Ready to Move        Resale     Unfurnished           NaN
1       Ready to Move        Resale  Semi-Furnished          East
2       Ready to Move        Resale     Unfurnished          East
3       Ready to Move        Resale     Unfurnished           NaN
4       Ready to Move        Resale     Unfurnished          West
...               ...           ...             ...           ...
187526  Ready to Move  New Property  Semi-Furnished          East
187527  Ready to Move        Resale     Unfurnished  North - East
187528  Ready to Move        Resale       Furnished          East
187529  Ready to Move        Resale  Semi-Furnished           NaN
187530  Ready to Move        Resale  Semi-Furnished  North - East

                   overlooking                              Society Bathroom  \
0                          NaN  Srushti Siddhi Mangal Murti Complex        1
1                  Garden/Park                          Dosti Vihar        2
2                  Garden/Park                 Sunrise by Kalpataru        2
3                          NaN                                  NaN        1
4       Garden/Park, Main Road          TenX Habitat Raymond Realty        2
...                        ...                                  ...      ...
187526             Garden/Park                    Bollywood Esencia        3
187527  Garden/Park, Main Road                   Sushma Urban Views        3
187528  Garden/Park, Main Road                    Bollywood Esencia        3
187529               Main Road                      Friends Enclave        2
187530       Garden/Park, Pool                      Affinity Greens        4

       Balcony Car Parking             Ownership Super Area  Dimensions  \
0            2         NaN                   NaN        NaN         NaN
1          NaN      1 Open              Freehold        NaN         NaN
2          NaN   1 Covered              Freehold        NaN         NaN
3            1         NaN                   NaN        NaN         NaN
4          NaN   1 Covered  Co-operative Society        NaN         NaN
...        ...         ...                   ...        ...         ...
187526       3   1 Covered              Freehold  1953 sqft         NaN
187527     NaN   1 Covered                   NaN  1680 sqft         NaN
187528       2  1 Covered,              Freehold        NaN         NaN
187529     NaN         NaN                   NaN   709 sqft         NaN
187530       4   1 Covered              Freehold  1915 sqft         NaN

        Plot Area Current_Floor Total_Floors
0             NaN            10           11
1             NaN             3           22
2             NaN            10           29
3             NaN             1            3
4             NaN            20           42
...           ...           ...          ...
187526        NaN             2            4
187527        NaN             4            6
187528        NaN             1            3
187529        NaN             2            2
187530        NaN             5           13

[187531 rows x 19 columns]

In [ ]:
# Used to identify the datatype
print(type(df))
# Used to identify total rows and column
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
(187531, 19)
  Amount(in rupees)  Price (in rupees) location Carpet Area         Status  \
0           42 Lac              6000.0    thane    500 sqft  Ready to Move
1           98 Lac             13799.0    thane    473 sqft  Ready to Move
2          1.40 Cr             17500.0    thane    779 sqft  Ready to Move
3           25 Lac                 NaN    thane    530 sqft  Ready to Move
4          1.60 Cr             18824.0    thane    635 sqft  Ready to Move

  Transaction      Furnishing facing             overlooking  \
0      Resale     Unfurnished    NaN                     NaN
1      Resale  Semi-Furnished   East             Garden/Park
2      Resale     Unfurnished   East             Garden/Park
3      Resale     Unfurnished    NaN                     NaN
4      Resale     Unfurnished   West  Garden/Park, Main Road

                               Society Bathroom Balcony Car Parking  \
0  Srushti Siddhi Mangal Murti Complex        1       2         NaN
1                          Dosti Vihar        2     NaN      1 Open
2                 Sunrise by Kalpataru        2     NaN   1 Covered
3                                  NaN        1       1         NaN
4          TenX Habitat Raymond Realty        2     NaN   1 Covered

              Ownership Super Area  Dimensions  Plot Area Current_Floor  \
0                   NaN        NaN         NaN        NaN            10
1              Freehold        NaN         NaN        NaN             3
2              Freehold        NaN         NaN        NaN            10
3                   NaN        NaN         NaN        NaN             1
4  Co-operative Society        NaN         NaN        NaN            20

  Total_Floors
0           11
1           22
2           29
3            3
4           42

In [6]:
# Used to print the first five data from the dataset
df.head(10)

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN
5,5,1 BHK Ready to Occupy Flat for sale in Virat A...,Creatively planned and constructed is a 1 BHK ...,45 Lac,6618.0,thane,NaN,Ready to Move,2 out of 7,Resale,...,East,"Garden/Park, Main Road",Virat Aangan,1,1,NaN,Co-operative Society,680 sqft,NaN,NaN
6,6,1 BHK Ready to Occupy Flat for sale Mumbra,This magnificent 1 BHK Flat is available for s...,16.5 Lac,2538.0,thane,550 sqft,Ready to Move,4 out of 5,Resale,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1 BHK Ready to Occupy Flat for sale Kalwa,Creatively planned and constructed is a 1 BHK ...,60 Lac,10435.0,thane,NaN,Ready to Move,Ground out of 7,Resale,...,NaN,NaN,NaN,1,NaN,NaN,NaN,575 sqft,NaN,NaN
8,8,1 BHK Ready to Occupy Flat for sale Kalwa,Discover this immaculate 1 BHK flat for sale a...,60 Lac,10000.0,thane,NaN,Ready to Move,Ground out of 2,Resale,...,NaN,NaN,NaN,1,NaN,NaN,Co-operative Society,600 sqft,NaN,NaN
9,9,3 BHK Ready to Occupy Flat for sale in Pride P...,One can find this stunning 3 BHK flat for sale...,1.60 Cr,11150.0,thane,900 sqft,Ready to Move,3 out of 27,Resale,...,East,Garden/Park,Pride Palms,3,1,1 Covered,Freehold,NaN,NaN,NaN

In [8]:
df.tail(10)

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
116036,116036,2 BHK Ready to Occupy Flat for sale Azad Nagar...,Discover this immaculate 2 BHK flat for sale a...,30 Lac,5128.0,new-delhi,NaN,Ready to Move,Ground out of 4,Resale,...,NaN,NaN,NaN,1,1,1 Open,NaN,65 sqyrd,NaN,NaN
116037,116037,1 BHK Ready to Occupy Flat for sale in DDA Sar...,This lovely 1 BHK Flat in Indraprastha Extensi...,75 Lac,8824.0,new-delhi,700 sqft,Ready to Move,2 out of 3,Resale,...,North - East,Main Road,DDA Saraswati Kunj Apartment,2,1,1 Open,Freehold,NaN,NaN,NaN
116038,116038,4 BHK Ready to Occupy Flat for sale Hauz Khas ...,One can find this stunning 4 BHK flat for sale...,21.35 Cr,23722.0,new-delhi,NaN,Ready to Move,2 out of 4,New Property,...,North - East,Garden/Park,NaN,5,5,NaN,Freehold,1000 sqyrd,NaN,NaN
116039,116039,4 BHK Ready to Occupy Flat for sale Hauz Khas ...,"This lovely 4 BHK Flat in Hauz Khas Enclave, N...",21.40 Cr,23778.0,new-delhi,NaN,Ready to Move,2 out of 4,New Property,...,North - East,Garden/Park,NaN,5,5,NaN,Freehold,1000 sqyrd,NaN,NaN
116040,116040,3 BHK Ready to Occupy Flat for sale Preet Vihar,Creatively planned and constructed is a 3 BHK ...,3.25 Cr,18056.0,new-delhi,200 sqyrd,Ready to Move,2 out of 4,New Property,...,North,"Garden/Park, Main Road",NaN,2,1,"1 Covered,",Freehold,NaN,NaN,NaN
116041,116041,3 BHK Ready to Occupy Flat for sale in Gayatri...,"This lovely 3 BHK Flat in Dwarka Sector 10, Ne...",1.88 Cr,11059.0,new-delhi,1300 sqft,Ready to Move,4 out of 8,Resale,...,North - East,"Garden/Park, Main Road",Gayatri Appartment,2,4,"1 Covered,",Freehold,NaN,NaN,NaN
116042,116042,3 BHK Ready to Occupy Flat for sale in DDA Fla...,3 BHK flat available for sale in New Delhi in ...,1.65 Cr,8919.0,new-delhi,1450 sqft,Ready to Move,1 out of 4,Resale,...,North - West,Main Road,DDA Flats Sarita Vihar,2,1,NaN,Freehold,NaN,NaN,NaN
116043,116043,3 BHK Ready to Occupy Flat for sale in Anekant...,Have a look at this immaculate 3 BHK flat for ...,90 Lac,6923.0,new-delhi,1200 sqft,Ready to Move,3 out of 4,Resale,...,East,"Garden/Park, Main Road",Anekant Apartment,3,2,NaN,Freehold,NaN,NaN,NaN
116044,116044,3 BHK Ready to Occupy Flat for sale Chittaranj...,"Chittaranjan Park, New Delhi has an attractive...",2 Cr,17778.0,new-delhi,1000 sqft,Ready to Move,1 out of 4,Resale,...,East,"Garden/Park, Main Road",NaN,3,3,NaN,Freehold,NaN,NaN,NaN
116045,116045,3 BHK Ready to Occupy Flat for sale in Fancy A...,3 BHK flat available for sale in New Delhi in ...,1.60 Cr,11429.0,new-delhi,1250 sqft,Ready to Move,1 out of 7,Resale,...,NaN,NaN,Fancy Apartments,2,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Gives all the datatypes of the columns
df.dtypes

Amount(in rupees)     object
Price (in rupees)    float64
location              object
Carpet Area           object
Status                object
Transaction           object
Furnishing            object
facing                object
overlooking           object
Society               object
Bathroom              object
Balcony               object
Car Parking           object
Ownership             object
Super Area            object
Dimensions           float64
Plot Area            float64
Current_Floor         object
Total_Floors          object
dtype: object

In [ ]:
# Sum of all NULL Values in the columns
df.isnull().sum()

Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
Current_Floor          7077
Total_Floors           7126
dtype: int64

In [ ]:
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Current_Floor,Total_Floors
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN,10,11
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN,3,22
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN,10,29
3,25 Lac,NaN,thane,530 sqft,Ready to Move,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,3
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,20,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,New Property,Semi-Furnished,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft,NaN,NaN,2,4
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,Resale,Unfurnished,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft,NaN,NaN,4,6
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,Resale,Furnished,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN,NaN,NaN,1,3
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,Resale,Semi-Furnished,NaN,Main Road,Friends Enclave,2,NaN,NaN,NaN,709 sqft,NaN,NaN,2,2
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft,NaN,NaN,5,13

In [ ]:
# Basic statistics
print(df.describe())

       Price (in rupees)  Dimensions  Plot Area
count       1.698660e+05         0.0        0.0
mean        7.583772e+03         NaN        NaN
std         2.724171e+04         NaN        NaN
min         0.000000e+00         NaN        NaN
25%         4.297000e+03         NaN        NaN
50%         6.034000e+03         NaN        NaN
75%         9.450000e+03         NaN        NaN
max         6.700000e+06         NaN        NaN

In [ ]:
# Find unique values
df['Carpet Area'].unique()

array(['500 sqft', '473 sqft', '779 sqft', ..., '1634 sqft', '164 sqyrd',
       '136 sqft'], shape=(2759,), dtype=object)

In [ ]:
df['Amount(in rupees)'].unique()

array(['42 Lac ', '98 Lac ', '1.40 Cr ', ..., '1.5 Lac ', '24.4 Lac ',
       '9.90 Cr '], shape=(1561,), dtype=object)

In [ ]:
df[['Area_value', 'Area_unit']] = df['Carpet Area'].str.split(expand=True)
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Current_Floor,Total_Floors,Area_value,Area_unit
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,2,NaN,NaN,NaN,NaN,NaN,10,11,500,sqft
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,...,NaN,1 Open,Freehold,NaN,NaN,NaN,3,22,473,sqft
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,...,NaN,1 Covered,Freehold,NaN,NaN,NaN,10,29,779,sqft
3,25 Lac,NaN,thane,530 sqft,Ready to Move,Resale,Unfurnished,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,1,3,530,sqft
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN,20,42,635,sqft
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,New Property,Semi-Furnished,East,Garden/Park,Bollywood Esencia,...,3,1 Covered,Freehold,1953 sqft,NaN,NaN,2,4,NaN,NaN
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,Resale,Unfurnished,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,1 Covered,NaN,1680 sqft,NaN,NaN,4,6,NaN,NaN
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,Resale,Furnished,East,"Garden/Park, Main Road",Bollywood Esencia,...,2,"1 Covered,",Freehold,NaN,NaN,NaN,1,3,1250,sqft
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,Resale,Semi-Furnished,NaN,Main Road,Friends Enclave,...,NaN,NaN,NaN,709 sqft,NaN,NaN,2,2,NaN,NaN
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",Affinity Greens,...,4,1 Covered,Freehold,1915 sqft,NaN,NaN,5,13,NaN,NaN

In [ ]:
df['Area_unit'].unique()

array(['sqft', nan, 'sqm', 'sqyrd', 'acre', 'ground', 'cent', 'bigha',
       'marla', 'kanal'], dtype=object)

In [ ]:
df[['Amount_value', 'Amount_unit']] = df['Amount(in rupees)'].str.split(n=1, expand=True)
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Ownership,Super Area,Dimensions,Plot Area,Current_Floor,Total_Floors,Area_value,Area_unit,Amount_value,Amount_unit
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,NaN,NaN,10,11,500,sqft,42,Lac
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,...,Freehold,NaN,NaN,NaN,3,22,473,sqft,98,Lac
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,...,Freehold,NaN,NaN,NaN,10,29,779,sqft,1.40,Cr
3,25 Lac,NaN,thane,530 sqft,Ready to Move,Resale,Unfurnished,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,3,530,sqft,25,Lac
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,Co-operative Society,NaN,NaN,NaN,20,42,635,sqft,1.60,Cr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,New Property,Semi-Furnished,East,Garden/Park,Bollywood Esencia,...,Freehold,1953 sqft,NaN,NaN,2,4,NaN,NaN,63,Lac
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,Resale,Unfurnished,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,1680 sqft,NaN,NaN,4,6,NaN,NaN,55,Lac
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,Resale,Furnished,East,"Garden/Park, Main Road",Bollywood Esencia,...,Freehold,NaN,NaN,NaN,1,3,1250,sqft,76,Lac
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,Resale,Semi-Furnished,NaN,Main Road,Friends Enclave,...,NaN,709 sqft,NaN,NaN,2,2,NaN,NaN,30,Lac
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",Affinity Greens,...,Freehold,1915 sqft,NaN,NaN,5,13,NaN,NaN,1.18,Cr

In [ ]:
df['Amount_unit'].unique()

array(['Lac ', 'Cr ', 'for Price'], dtype=object)

In [ ]:
df['Transaction'].unique()

array(['Resale', 'New Property', nan, 'Other', 'Rent/Lease'], dtype=object)

In [ ]:
df['Transaction'].isnull().sum()

np.int64(83)

In [ ]:
df['Transaction'] = df['Transaction'].fillna('Unknown')

In [ ]:
df['Transaction'].unique()

array(['Resale', 'New Property', 'Unknown', 'Other', 'Rent/Lease'],
      dtype=object)

In [ ]:
# Encode the data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le

LabelEncoder()

In [ ]:
df['Transaction'] = le.fit_transform(df['Transaction'])
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Ownership,Super Area,Dimensions,Plot Area,Current_Floor,Total_Floors,Area_value,Area_unit,Amount_value,Amount_unit
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,3,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,NaN,NaN,10,11,500,sqft,42,Lac
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3,Semi-Furnished,East,Garden/Park,Dosti Vihar,...,Freehold,NaN,NaN,NaN,3,22,473,sqft,98,Lac
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,3,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,...,Freehold,NaN,NaN,NaN,10,29,779,sqft,1.40,Cr
3,25 Lac,NaN,thane,530 sqft,Ready to Move,3,Unfurnished,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,3,530,sqft,25,Lac
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,3,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,Co-operative Society,NaN,NaN,NaN,20,42,635,sqft,1.60,Cr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,0,Semi-Furnished,East,Garden/Park,Bollywood Esencia,...,Freehold,1953 sqft,NaN,NaN,2,4,NaN,NaN,63,Lac
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,3,Unfurnished,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,1680 sqft,NaN,NaN,4,6,NaN,NaN,55,Lac
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,3,Furnished,East,"Garden/Park, Main Road",Bollywood Esencia,...,Freehold,NaN,NaN,NaN,1,3,1250,sqft,76,Lac
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,3,Semi-Furnished,NaN,Main Road,Friends Enclave,...,NaN,709 sqft,NaN,NaN,2,2,NaN,NaN,30,Lac
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,3,Semi-Furnished,North - East,"Garden/Park, Pool",Affinity Greens,...,Freehold,1915 sqft,NaN,NaN,5,13,NaN,NaN,1.18,Cr

In [ ]:
print("Unique Elements :",df['Furnishing'].unique())
print("Null elements :", df['Furnishing'].isnull().sum())

Unique Elements : ['Unfurnished' 'Semi-Furnished' 'Furnished' nan]
Null elements : 2897

In [ ]:
df['Furnishing'] = df['Furnishing'].fillna('Unknown')
df['Furnishing'].unique()

array(['Unfurnished', 'Semi-Furnished', 'Furnished', 'Unknown'],
      dtype=object)

In [ ]:
df['Furnishing'] = le.fit_transform(df['Furnishing'])
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Ownership,Super Area,Dimensions,Plot Area,Current_Floor,Total_Floors,Area_value,Area_unit,Amount_value,Amount_unit
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,3,2,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,NaN,NaN,10,11,500,sqft,42,Lac
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3,1,East,Garden/Park,Dosti Vihar,...,Freehold,NaN,NaN,NaN,3,22,473,sqft,98,Lac
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,3,2,East,Garden/Park,Sunrise by Kalpataru,...,Freehold,NaN,NaN,NaN,10,29,779,sqft,1.40,Cr
3,25 Lac,NaN,thane,530 sqft,Ready to Move,3,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,3,530,sqft,25,Lac
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,3,2,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,Co-operative Society,NaN,NaN,NaN,20,42,635,sqft,1.60,Cr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,0,1,East,Garden/Park,Bollywood Esencia,...,Freehold,1953 sqft,NaN,NaN,2,4,NaN,NaN,63,Lac
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,3,2,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,1680 sqft,NaN,NaN,4,6,NaN,NaN,55,Lac
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,3,0,East,"Garden/Park, Main Road",Bollywood Esencia,...,Freehold,NaN,NaN,NaN,1,3,1250,sqft,76,Lac
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,3,1,NaN,Main Road,Friends Enclave,...,NaN,709 sqft,NaN,NaN,2,2,NaN,NaN,30,Lac
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,3,1,North - East,"Garden/Park, Pool",Affinity Greens,...,Freehold,1915 sqft,NaN,NaN,5,13,NaN,NaN,1.18,Cr

In [ ]:
df['Super Area'].unique()

array([nan, '680 sqft', '575 sqft', ..., '2066 sqft', '406 sqft',
       '2332 sqft'], shape=(2977,), dtype=object)

In [ ]:
df[['Super_area_value' , 'Super_area_unit']] = df['Super Area'].str.split(n=1,expand=True)
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Dimensions,Plot Area,Current_Floor,Total_Floors,Area_value,Area_unit,Amount_value,Amount_unit,Super_area_value,Super_area_unit
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,3,2,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,10,11,500,sqft,42,Lac,NaN,NaN
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3,1,East,Garden/Park,Dosti Vihar,...,NaN,NaN,3,22,473,sqft,98,Lac,NaN,NaN
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,3,2,East,Garden/Park,Sunrise by Kalpataru,...,NaN,NaN,10,29,779,sqft,1.40,Cr,NaN,NaN
3,25 Lac,NaN,thane,530 sqft,Ready to Move,3,2,NaN,NaN,NaN,...,NaN,NaN,1,3,530,sqft,25,Lac,NaN,NaN
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,3,2,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,NaN,NaN,20,42,635,sqft,1.60,Cr,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,0,1,East,Garden/Park,Bollywood Esencia,...,NaN,NaN,2,4,NaN,NaN,63,Lac,1953,sqft
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,3,2,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,NaN,4,6,NaN,NaN,55,Lac,1680,sqft
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,3,0,East,"Garden/Park, Main Road",Bollywood Esencia,...,NaN,NaN,1,3,1250,sqft,76,Lac,NaN,NaN
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,3,1,NaN,Main Road,Friends Enclave,...,NaN,NaN,2,2,NaN,NaN,30,Lac,709,sqft
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,3,1,North - East,"Garden/Park, Pool",Affinity Greens,...,NaN,NaN,5,13,NaN,NaN,1.18,Cr,1915,sqft

In [ ]:
df['Super_area_unit'] = df['Super_area_unit'].fillna('Unknown')
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Dimensions,Plot Area,Current_Floor,Total_Floors,Area_value,Area_unit,Amount_value,Amount_unit,Super_area_value,Super_area_unit
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,3,2,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,10,11,500,sqft,42,Lac,NaN,Unknown
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3,1,East,Garden/Park,Dosti Vihar,...,NaN,NaN,3,22,473,sqft,98,Lac,NaN,Unknown
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,3,2,East,Garden/Park,Sunrise by Kalpataru,...,NaN,NaN,10,29,779,sqft,1.40,Cr,NaN,Unknown
3,25 Lac,NaN,thane,530 sqft,Ready to Move,3,2,NaN,NaN,NaN,...,NaN,NaN,1,3,530,sqft,25,Lac,NaN,Unknown
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,3,2,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,NaN,NaN,20,42,635,sqft,1.60,Cr,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,0,1,East,Garden/Park,Bollywood Esencia,...,NaN,NaN,2,4,NaN,NaN,63,Lac,1953,sqft
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,3,2,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,NaN,4,6,NaN,NaN,55,Lac,1680,sqft
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,3,0,East,"Garden/Park, Main Road",Bollywood Esencia,...,NaN,NaN,1,3,1250,sqft,76,Lac,NaN,Unknown
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,3,1,NaN,Main Road,Friends Enclave,...,NaN,NaN,2,2,NaN,NaN,30,Lac,709,sqft
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,3,1,North - East,"Garden/Park, Pool",Affinity Greens,...,NaN,NaN,5,13,NaN,NaN,1.18,Cr,1915,sqft

In [ ]:
df['Super_area_value'] = df['Super_area_value'].fillna(0)
df.head()

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Dimensions,Plot Area,Current_Floor,Total_Floors,Area_value,Area_unit,Amount_value,Amount_unit,Super_area_value,Super_area_unit
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,3,2,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,10,11,500,sqft,42,Lac,0,Unknown
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3,1,East,Garden/Park,Dosti Vihar,...,NaN,NaN,3,22,473,sqft,98,Lac,0,Unknown
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,3,2,East,Garden/Park,Sunrise by Kalpataru,...,NaN,NaN,10,29,779,sqft,1.40,Cr,0,Unknown
3,25 Lac,NaN,thane,530 sqft,Ready to Move,3,2,NaN,NaN,NaN,...,NaN,NaN,1,3,530,sqft,25,Lac,0,Unknown
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,3,2,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,NaN,NaN,20,42,635,sqft,1.60,Cr,0,Unknown

In [ ]:
df['Super_area_unit'].unique()

array(['Unknown', 'sqft', 'sqm', 'sqyrd', 'marla', 'kanal', 'ground',
       'biswa2', 'aankadam', 'acre', 'hectare', 'cent'], dtype=object)

In [ ]:
df['Area_unit'].unique()

array(['sqft', nan, 'sqm', 'sqyrd', 'acre', 'ground', 'cent', 'bigha',
       'marla', 'kanal'], dtype=object)

In [ ]:
import numpy as np

# Ensure conversion map is defined
conversion_to_sqft = {
    'sqft': 1,
    'sqm': 10.7639,
    'sqyrd': 9,
    'acre': 43560,
    'ground': 2400,
    'cent': 435.6,
    'bigha': 27225,
    'marla': 272.25,
    'kanal': 5445
}

# Convert safely
df['Area_value_sqft'] = df.apply(
    lambda row: (
        float(row['Area_value']) * conversion_to_sqft.get(str(row['Area_unit']).strip().lower(), np.nan)
        if pd.notnull(row['Area_value']) and pd.notnull(row['Area_unit'])
        else np.nan
    ),
    axis=1
)

In [ ]:
df.drop(columns=['Area_value'], axis=1, inplace=True)
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Dimensions,Plot Area,Current_Floor,Total_Floors,Area_unit,Amount_value,Amount_unit,Super_area_value,Super_area_unit,Area_value_sqft
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,3,2,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,10,11,sqft,42,Lac,0,Unknown,500.0
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3,1,East,Garden/Park,Dosti Vihar,...,NaN,NaN,3,22,sqft,98,Lac,0,Unknown,473.0
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,3,2,East,Garden/Park,Sunrise by Kalpataru,...,NaN,NaN,10,29,sqft,1.40,Cr,0,Unknown,779.0
3,25 Lac,NaN,thane,530 sqft,Ready to Move,3,2,NaN,NaN,NaN,...,NaN,NaN,1,3,sqft,25,Lac,0,Unknown,530.0
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,3,2,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,NaN,NaN,20,42,sqft,1.60,Cr,0,Unknown,635.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,0,1,East,Garden/Park,Bollywood Esencia,...,NaN,NaN,2,4,NaN,63,Lac,1953,sqft,NaN
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,3,2,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,NaN,4,6,NaN,55,Lac,1680,sqft,NaN
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,3,0,East,"Garden/Park, Main Road",Bollywood Esencia,...,NaN,NaN,1,3,sqft,76,Lac,0,Unknown,1250.0
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,3,1,NaN,Main Road,Friends Enclave,...,NaN,NaN,2,2,NaN,30,Lac,709,sqft,NaN
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,3,1,North - East,"Garden/Park, Pool",Affinity Greens,...,NaN,NaN,5,13,NaN,1.18,Cr,1915,sqft,NaN

In [ ]:
df.drop(columns=['Dimensions', 'Plot Area'], axis=1, inplace=True)
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Ownership,Super Area,Current_Floor,Total_Floors,Area_unit,Amount_value,Amount_unit,Super_area_value,Super_area_unit,Area_value_sqft
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,3,2,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,10,11,sqft,42,Lac,0,Unknown,500.0
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3,1,East,Garden/Park,Dosti Vihar,...,Freehold,NaN,3,22,sqft,98,Lac,0,Unknown,473.0
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,3,2,East,Garden/Park,Sunrise by Kalpataru,...,Freehold,NaN,10,29,sqft,1.40,Cr,0,Unknown,779.0
3,25 Lac,NaN,thane,530 sqft,Ready to Move,3,2,NaN,NaN,NaN,...,NaN,NaN,1,3,sqft,25,Lac,0,Unknown,530.0
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,3,2,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,Co-operative Society,NaN,20,42,sqft,1.60,Cr,0,Unknown,635.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,0,1,East,Garden/Park,Bollywood Esencia,...,Freehold,1953 sqft,2,4,NaN,63,Lac,1953,sqft,NaN
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,3,2,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,1680 sqft,4,6,NaN,55,Lac,1680,sqft,NaN
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,3,0,East,"Garden/Park, Main Road",Bollywood Esencia,...,Freehold,NaN,1,3,sqft,76,Lac,0,Unknown,1250.0
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,3,1,NaN,Main Road,Friends Enclave,...,NaN,709 sqft,2,2,NaN,30,Lac,709,sqft,NaN
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,3,1,North - East,"Garden/Park, Pool",Affinity Greens,...,Freehold,1915 sqft,5,13,NaN,1.18,Cr,1915,sqft,NaN

In [ ]:
df.columns

Index(['Amount(in rupees)', 'Price (in rupees)', 'location', 'Carpet Area',
       'Status', 'Transaction', 'Furnishing', 'facing', 'overlooking',
       'Society', 'Bathroom', 'Balcony', 'Car Parking', 'Ownership',
       'Super Area', 'Current_Floor', 'Total_Floors', 'Area_unit',
       'Amount_value', 'Amount_unit', 'Super_area_value', 'Super_area_unit',
       'Area_value_sqft'],
      dtype='object')

In [ ]:
df['facing'].unique()
df['facing'].fillna('Unknown')
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,...,Ownership,Super Area,Current_Floor,Total_Floors,Area_unit,Amount_value,Amount_unit,Super_area_value,Super_area_unit,Area_value_sqft
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,3,2,NaN,NaN,Srushti Siddhi Mangal Murti Complex,...,NaN,NaN,10,11,sqft,42,Lac,0,Unknown,500.0
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3,1,East,Garden/Park,Dosti Vihar,...,Freehold,NaN,3,22,sqft,98,Lac,0,Unknown,473.0
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,3,2,East,Garden/Park,Sunrise by Kalpataru,...,Freehold,NaN,10,29,sqft,1.40,Cr,0,Unknown,779.0
3,25 Lac,NaN,thane,530 sqft,Ready to Move,3,2,NaN,NaN,NaN,...,NaN,NaN,1,3,sqft,25,Lac,0,Unknown,530.0
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,3,2,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,...,Co-operative Society,NaN,20,42,sqft,1.60,Cr,0,Unknown,635.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,0,1,East,Garden/Park,Bollywood Esencia,...,Freehold,1953 sqft,2,4,NaN,63,Lac,1953,sqft,NaN
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,3,2,North - East,"Garden/Park, Main Road",Sushma Urban Views,...,NaN,1680 sqft,4,6,NaN,55,Lac,1680,sqft,NaN
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,3,0,East,"Garden/Park, Main Road",Bollywood Esencia,...,Freehold,NaN,1,3,sqft,76,Lac,0,Unknown,1250.0
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,3,1,NaN,Main Road,Friends Enclave,...,NaN,709 sqft,2,2,NaN,30,Lac,709,sqft,NaN
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,3,1,North - East,"Garden/Park, Pool",Affinity Greens,...,Freehold,1915 sqft,5,13,NaN,1.18,Cr,1915,sqft,NaN